### ISSUE TITLE
evaluate() got an unexpected keyword argument 'gpu_collect' while training clipiqa_coop_koniq

### ISSUE THREAD

**Issue by ganeshpulivendula1985** [IceClear/CLIP-IQA#18]
python tools/train.py configs/clipiqa/clipiqa_coop_koniq.py

2023-10-16 08:47:54,004 - mmedit - INFO - workflow: [('train', 1)], max: 500 iters
2023-10-16 08:47:54,004 - mmedit - INFO - Checkpoints will be saved to C:\Users\pdo-labuser\CLIP-IQA\work_dirs\clipiqa_coop_koniq by HardDiskBackend.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2015/2015, 17.2 task/s, elapsed: 117s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 135, in main
    train_model(
  File "c:\users\pdo-labuser\clip-iqa\mmedit\apis\train.py", line 106, in train_model
    _non_dist_train(
  File "c:\users\pdo-labuser\clip-iqa\mmedit\apis\train.py", line 362, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "C:\Users\pdo-labuser\anaconda3\envs\clipiqa\lib\site-packages\mmcv\runner\iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "C:\Users\pdo-labuser\anaconda3\envs\clipiqa\lib\site-packages\mmcv\runner\iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "C:\Users\pdo-labuser\anaconda3\envs\clipiqa\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "c:\users\pdo-labuser\clip-iqa\mmedit\core\evaluation\eval_hooks.py", line 48, in after_train_iter
    self.evaluate(runner, results)
  File "c:\users\pdo-labuser\clip-iqa\mmedit\core\evaluation\eval_hooks.py", line 57, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

Please help with resolution

**Comment by IceClear** [comment]
I did not meet such a problem. It seems that you are not using the right env. You may switch to another repo for test. See #13

**Comment by lmc2000** [comment]
I also meet such a problem
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 135, in main
    train_model(
  File "/home/www/application/models/CLIP-IQA/mmedit/apis/train.py", line 106, in train_model
    _non_dist_train(
  File "/home/www/application/models/CLIP-IQA/mmedit/apis/train.py", line 362, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/www/application/miniconda3/envs/clipiqa/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/www/application/miniconda3/envs/clipiqa/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/www/application/miniconda3/envs/clipiqa/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/www/application/models/CLIP-IQA/mmedit/core/evaluation/eval_hooks.py", line 48, in after_train_iter
    self.evaluate(runner, results)
  File "/home/www/application/models/CLIP-IQA/mmedit/core/evaluation/eval_hooks.py", line 57, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'
